#!/usr/bin/env bash
#what is this for

COUNT=1
while [ $COUNT -lt 11 ]
do
    if [ $COUNT = 4 ]
    then
        echo "bad luck"
    elif [ $COUNT = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let COUNT+=1
done
