#!/usr/bin/env bash
#what is this for

FILES="holbertonschool"

if [ -e "$FILES" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "$FILES" ]
    then
        echo "holbertonschool file is empty"
    else
        echo "holbertonschool file is not empty"
    fi
    if [ -f "$FILES" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
